/* eslint-disable no-multi-str */
/* eslint-disable no-useless-escape */

export const introduction = 'I recently completed an eight month co-op work term as a Software Developer at Magnet Forensics to complete my co-op experience. This blog will explore the tasks I completed, the goals I set for myself, the skills I gained, and the challenges I faced during my final two work terms as a co-op student.';

export const employerInformation = "Magnet Forensics (Magnet) is a digital forensics company based in Waterloo, Ontario, with offices all over the globe. Magnet was founded by former Waterloo Region Police Service digital forensics examiner Jad Saliba, and Adam Belsher, an eager business leader, in 2011 following Saliba’s creation of Internet Evidence Finder (IEF) - a data recovery solution geared toward retrieving digital evidence off a suspect’s hard drive.\
 With a mission to impact people’s lives by finding the truth and empowering others to make a difference, Magnet Forensics is committed to seeking justice, protecting the innocent, and bringing the truth to light. This dedication to making a real difference in the world is what drew me to Magnet, and what made coming to work each day a fulfilling and enjoyable experience over the course of the last eight months.\
Magnet Forensics has developed  a vast array of products aside from IEF- the most popular being Magnet Axiom, a complete digital forensics suite that will extract, process, and categorize data from phones, laptops, tablets, and computers, to allow forensics experts to view critical case information. Other products include Magnet Automate, a tool for automating digital forensics work flows to decrease forensics backlogs, Magnet Atlas, a digital evidence and case management solution, and Magnet Review, a product geared toward reviewing digital evidence from anywhere through an intuitive UI that allows evidence viewing, evidence categorizing, and report generation to present in court cases.";

export const jobDescription = "During my first semester at Magnet Forensics, I worked as a software developer co-op on the Software Tools and Systems (STS) team. This team primarily dealt with tooling and infrastructure that empowered developers on other teams and powered the products that the company developed. Because of this, there was no strict release schedule that work that the team completed had to adhere to, which was a workflow that I was not accustomed to. \
The majority of my efforts over the course of this semester contributed to an internal testing framework built in React- a Javascript framework that I was not familiar with. This aspect of my job on STS was by-far my favorite, as it exposed me to web development in React. I was also tasked with working on tickets involving Jenkins, a project automation tool, which was completely unfamiliar to me. This aspect of my job opened my eyes to the complexity of project automation and deployment systems, which has made me more comfortable as a developer, as I was completely unfamiliar with this territory. The third and final aspect of my duties as a software developer on STS was maintaining the API that supported the React testing framework and Jenkins tool previously mentioned. I found that knowledge I learned during my post-secondary studies was most applicable in this area, specifically in object-oriented programming, resource-allocation, and algorithm efficiency in order to ensure that the code I wrote was efficient, understandable, and testable. \
For my second term at Magnet Forensics, I transitioned to the team working on Magnet Review, but continued to work as a software developer co-op. My experience on this team was much different than on STS, as this team has a semi-rigid release schedule, customer-requested features and bug fixes, and a time-zone difference to deal with, as part of the team is based in The Hague, Netherlands. This team also differed in that testing was a team-based effort, as opposed to the mostly individual effort which was exercised on STS. This was a new experience for me, as neither my previous academic nor co-op experiences had involved this style of testing. Over the course of the semester, I had the opportunity to work on all aspects of the product – frontend, backend, and APIs – allowing for me to gain a deep understanding of some specific parts of the product, while becoming comfortable working on all aspects of the product as a whole. This is commonly-referred to as being “T-shaped”, and is a value that the Review team focuses on significantly. I feel \
that I could have done more “deep-diving” into the product in order to become specialized in a higher-level aspect of the product, but this posed a challenge with only four months to spend on the team. I also had the opportunity to work with a small team of developers on performance testing during my time on Review. This endeavor exposed me to working with Amazon Web Services, automated user-interface testing, and understanding how different hardware configurations can affect performance as a whole. This work was especially interesting in that it allowed me to investigate how different aspects of the product performed, and allowed me to discover methods of increasing performance that I didn’t know were possible with the product. Overall, the variety of work that was available on this team resulted in constant excitement towards the work I was doing, as each task differed from the last. Working with the Review team had me excited to come into work everyday to tackle the problems that we faced together.";

export const goals = [
	"During my first semester, I chose to set more technical goals for myself, as I was working with a tech stack that I was completely unfamiliar with. My first goal was to gain experience developing and enhancing web applications using React and Redux. To achieve this goal, I worked to pick up front-end tickets that I felt were within my abilities to complete, and asked for assistance when necessary if a ticket was challenging. By the end of my first semester at Magnet, I felt that I had achieved this goal. I adhered to plans on how to achieve this goal, and became very comfortable working with React and Redux by completing tickets of varying difficulty and asking my mentor for assistance and advice whenever necessary. The vast majority of the tickets I completed on STS, approximately seventy-eight percent, involved working with React and Redux, which I feel shows how much I was able to worth with these frameworks.",
	"My second goal while on STS was to improve my written communication skills by providing my team members with useful feedback when performing code reviews and documenting my own work. To complete this goal, I planned to review my team members’ code that I felt I could understand in a short period of time, and could provide meaningful comments and insight into. I felt that this goal was successfully completed by the end of my first semester, to an extent. I feel that by providing useful comments for all code that I wrote that I was able to expedite my coworkers\' review process on my own code, as it enabled them to quickly understand the intention of methods and classes that may not have been apparent at first glance. I reviewed fellow team members\' code whenever I had the chance, which provided great experience in familiarizing myself with others' code bases quickly and efficiently to review their updates; however,\
	I didn’t feel that I had logged as many hours reviewing code as I had intended to by the end of the semester. Because of this, I chose to continue working towards this goal during my time on Review.",
	"My third goal was to gain experience creating unit tests for all code that I wrote. At previous co-op placements, testing was not a focus of the teams that I worked on, and so I was never able to gain experience writing tests with a high percentage of code-coverage, or tests that would be included in automated build processes. To achieve this goal, I planned to test all functions, components, and logic that I introduced while on the Software Tools and Systems team. By the end of the semester, I felt that I had successfully achieved this goal.  Seeing as I had no experience writing unit tests prior to this co-op term, I feel I'm very capable of doing so now, and feel that working towards this goal has made me think of how I implement solutions to complex problems in order to ensure testability. I was able to gain experience working with testing frameworks in C#, React, and Python, and achieved over eighty percent code \
	coverage in my tests once I started using our code-coverage tool to measure how my tests performed, which I am very proud of.",
	"My fourth, and final goal during my time on STS was to become more experienced tracking unwanted behavior in Jenkins builds and jobs to improve their performance and efficiency wherever possible. To achieve this goal, I planned to work through tickets pertaining to Jenkins jobs and gain an understanding of how the build system worked to be able to track unwanted behavior efficiently. I feel that I was able to achieve this goal to some degree, but that there was room for improvement yet. There were some issues I was not able to diagnose causes for, due to their complexity, but I was capable of diagnosing and fixing less-complex issues that occurred throughout the semester. I feel that four months time may not have been sufficient to achieve this goal fully.",
	"During my second semester at Magnet, I chose to focus on both technical and communication goals. In order to aid in measuring the following goals, I sent out a survey to my fellow team  members to gain their perspectives on how they felt I contributed to the team in the areas that my goals focused on.",
	"As I wasn’t able to fully-complete my code review goal to the extent that I had hoped last semester, I chose to continue honing my skills in that area. To achieve this goal, I worked to become a more proficient code reviewer and work to be able to have meaningful and helpful suggestions when reviewing others\' work. To achieve this I planned to perform code reviews whenever possible and make a considerable effort to make suggestions to improve efficiency and readability whenever possible. I also planned to ask why certain patterns were chosen in place of others to gain a deeper understanding of decision-making to improve upon my own work. At the end of my time on Review, the survey that I sent to my fellow team members indicated that I was successful in achieving this goal, which echoes how I feel. I gained valuable insight into decisions that were made when implementing new features or refactoring old code, and was\
	able to spark helpful discussions with my reviews over the course of the semester.",
	"My second goal during my time on Review was to collaborate with others to help the team deliver on features and fixes more quickly, while gaining experience coding with another team member. To achieve this goal, I communicated that I was available to help drive work that was in-progress to completion through pairing on tickets. By the end of the semester, I felt that I achieved this goal to its full potential - I was able to pair with fellow team members on multiple occasions to complete large tickets, and gained valuable experience splitting work into manageable slices. The survey that I sent to my co-workers indicated that I was very successful in this area. Suggestions that I received pertaining to this goal were to stop apologizing for my lack of experience when working on unfamiliar tasks, and to continue with my collaboration efforts, which I plan to do when I enter the workforce post-graduation.",
	"My third goal was to become experienced in testing other people\'s code by the end of the semester. There was a lot of opportunity to work towards this goal, as build verification testing was completed as a team prior to each release, and testing was completed on each ticket prior to being landed to the product’s master branch. To achieve this goal, I contributed to build verification testing, and quality assurance as a whole, whenever possible. I asked for assistance from both developers and testers on the team whenever necessary to ensure my testing efforts were covering sufficient test cases. I felt that I gained an extensive amount of experience in testing during my time on Review, which allowed me to complete this goal with ease. My survey indicated that I was successful in completing this goal as well, and some suggestions that were brought forth included continuing making an effort to test others’ code, as it\
	contributes to growth as a developer, and continuing to keep thorough notes and test plans when working in this area. I value that this goal made me realize that development will continue to be my path in the computing industry, but I now value testing experience to a higher degree, as it attributes to a higher understanding of the product that I am working on.",
	"My fourth and final goal during my time on Review was to be more vocal of my opinions and ideas in a team setting. This goal was added later into my time on Review as a result of a performance evaluation that was completed in the middle of my term, as my mentor and supervisor indicated that I should voice my opinion on discussions during team planning, standup, and retrospective meetings. In order to achieve this goal, I strived to speak my mind at least once per meeting, under the condition that my input was valuable, and not just input contributed for the sake of doing so. In working towards this goal, I made an effort to ponder on suggestions that were brought forth in meetings and ask valuable questions to broaden my understanding of concepts that I was unfamiliar with, as well as provide my feedback on ideas whenever appropriate. I feel I was successful in speaking up more in meetings by the end of the term,\
	specifically due to being able to work for an extended duration on a large performance evaluation task. The survey I sent to my coworkers indicated that I was successful in improving upon this over the course of the semester as I had hoped to. Working towards this goal was very valuable in that it provided me with more confidence as a developer on the team by having my voice heard, and questions answered. Overall, this goal made me more comfortable working with my team as a whole."
];

export const conclusion = "To put it simply, my semesters at Magnet Forensics were amazing. Magnet provided exactly what I was looking for in my final co-op terms - experience working with knowledgeable, passionate individuals towards a common goal of making a real difference in the world. This made each day an experience to look forward to, and made me love my work. Through completing goals that were set for each semester, I was able to expand my technical knowledge to a point where I am much more confident in my skills as a developer, while honing my soft skills pertaining to both written and verbal communication. I feel that Magnet has provided me with a sense of confidence that will help me catch my stride when I enter the workforce post-graduation, and for that I am extremely grateful. \
My time at Magnet allowed me to gain experience working on entire web-based products, internal tooling infrastructure, and development tools and platforms such as Gitlab, Jenkins,and Gerrit, that made me a more efficient developer. I was able to apply much of the knowledge that I learned in my academic studies in many aspects of my day-to-day tasks, and was provided with an opportunity to expand my soft-skills through pairing with other developers on tickets, reviewing and testing other developers’ code, and coordinating meetings pertaining to tickets I was working on. I look forward to exercising the skills that I have developed during my eight months at Magnet Forensics during my final eight months of academic studies, and for the duration of my career in computing.";

export const acknowledgements = "I would like to thank my mentors Adam Feher and Andrew Welton, from the STS and Review teams respectively, for their guidance during my time at Magnet. Their patience with my almost-constant stream of questions and willingness to explain unfamiliar concepts in order to aid my understanding were greatly-appreciated. Their technical-knowledge of their respective teams’ infrastructure was invaluable when I needed advice on feature implementation details and issues that arose throughout the terms. In particular, I’d like to call out Adam for his fantastic ability to teach others - his methodical approach to explaining the intricacies of React and Redux resulted in a semester filled with learning and gaining valuable experience with those frameworks. I’d like to specifically thank Andrew for taking the time to go through in-depth reviews of my performance, allowing me to iterate on my goals \
for the semester on the Review team and improve targeted skill sets in order to drive career growth in the future.\
I would also like to thank my managers for each respective semester, Matthew Beamer and Jason Wood. Their leadership, guidance, and feedback made working on their teams extremely enjoyable and provided an atmosphere where I felt that my contributions to the work their teams were doing were valued.\
I’d like to also extend my thanks to Laura Gatto and Kate McRoberts for their dedication to the co-op program and their constant support with any questions and concerns I have had with matters related to co-op. Their support was extremely appreciated over the course of the last few years.\
Lastly, I would like to thank Dr. Greg Klotz for his continued assistance throughout the years. A special thank you goes to Doctor Klotz for reviewing this report as well.";
